samples_root_dir: "path/to/samples_dir"
output_dir: "path/to/results"
samples_extension: "pt"  # "pt", "npy"
songs_per_sample: 4
measures_per_song: 4
timesteps_per_measure: 48
beat_per_measure: 4
n_pitches: 88
hard_threshold: 0.5

n_tracks: 5
track_names:
- drum
- piano
- guitar
- bass
- strings

metrics:
    drum_pattern:
        name: DrumPattern
        args:
            songs_per_sample: ${songs_per_sample}
            measures_per_song: ${measures_per_song}
            track_names: ${track_names}
            target_track_index: 0
            timesteps_per_measure: ${timesteps_per_measure}
    empty_bar_rate:
        name: EmptyBarRate
        args:
            songs_per_sample: ${songs_per_sample}
            measures_per_song: ${measures_per_song}
            track_names: ${track_names}
    used_pitch_classes:
        name: UsedPitchClasses
        args:
            songs_per_sample: ${songs_per_sample}
            measures_per_song: ${measures_per_song}
            track_names: ${track_names}
    tonal_distance:
        name: TonalDistance
        args:
            songs_per_sample: ${songs_per_sample}
            measures_per_song: ${measures_per_song}
            track_names: ${track_names}
            timesteps_per_measure: ${timesteps_per_measure}
            beat_per_measure: ${beat_per_measure}

defaults:
    - evaluation_loader: ndarray_from_pt
    - reshaper: musediff_reshaper
    - stats: calculate_track_statistics

